# Generated by Django 4.2.11 on 2024-11-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
