# Generated by Django 4.2.11 on 2024-11-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_document_profile_picture_department_name_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='surname_en',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_en',
        ),
    ]
