# Generated by Django 4.2.11 on 2024-11-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
