# Generated by Django 4.2.11 on 2024-11-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_department_name_az_department_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name_en',
        ),
    ]
