# Generated by Django 5.1.2 on 2024-11-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_department_name_az_remove_department_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='amount_az',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='amount_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_az',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_en',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offboardingitem',
            name='item_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offboardingitem',
            name='item_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='item_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='item_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
