# Generated by Django 4.2.11 on 2024-11-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_attendance_status_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
    ]
