# Generated by Django 4.2.11 on 2024-11-04 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_az',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.position'),
        ),
    ]
