# Generated by Django 4.2.11 on 2024-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_employee_department_az_employee_department_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status_az',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='amount_az',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='amount_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_az',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_en',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='message',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='offboardingitem',
            name='item_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offboardingitem',
            name='item_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='item_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='item_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='comments_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='training_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
