# Generated by Django 4.2.11 on 2024-11-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attendance_status_az_attendance_status_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status_az',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='amount_az',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='amount_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_az',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='offboardingitem',
            name='item_az',
        ),
        migrations.RemoveField(
            model_name='offboardingitem',
            name='item_en',
        ),
        migrations.RemoveField(
            model_name='onboardingitem',
            name='item_az',
        ),
        migrations.RemoveField(
            model_name='onboardingitem',
            name='item_en',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='comments_az',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='comments_en',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_name_az',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_name_en',
        ),
    ]
