# Generated by Django 4.2.11 on 2024-11-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_attendance_status_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_en',
        ),
    ]
