# Generated by Django 4.2.11 on 2024-11-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employee_created_at_az_employee_created_at_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at_az',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at_en',
        ),
    ]
