# Generated by Django 4.2.11 on 2024-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animals',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
